insert into Person(firstName,lastName) values('Roman','Ryabec')
insert into Person(firstName,lastName) values('Roman','Ryabec')
insert into Person(firstName,lastName) values('Roman','Ryabec')
insert into Person(firstName,lastName) values('Roman','Ryabec')
insert into Person(firstName,lastName) values('Roman','Ryabec')